global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['ipv4addressofdockerhost:9090']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
